name: Build Stories App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Package
        run: |
          mkdir -p output
          zip -r output/Stories_Project.zip . -x "*.git*"
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: StoriesApp-Package
          path: output/Stories_Project.zip
